version: '3.7'

services:
  database:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: book-store-go-app
    depends_on: 
      - database
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WAIT_HOSTS: mysql-db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
    ports:
      - "8000:8000"
    networks:
      - mynet

networks:
  mynet: